---
abstract: 'Pod Web Server based on Catalyst and ExtJS'
author:
  - 'Moritz Onken'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Pod-Browser
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::POD: 0.02002
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7014
  YAML::Syck: 0
  parent: 0
version: 0.02
